# The URL the site will be built for
base_url = "https://hermanradtke.com"

generate_feed = true

build_search_index = true

title = "Herman J. Radtke III"
theme = "anpu"

taxonomies = [
    { name = "categories" },
    { name = "tags" },
]

[markdown]
highlight_code = true

[extra]
anpu_menu_links = [
    { url = "$BASE_URL/about", name = "About" },
    { url = "$BASE_URL/projects", name = "Projects" },
    { url = "$BASE_URL/talks", name = "Talks" },
    { url = "$BASE_URL/tags", name = "Tags" },
    { url = "$BASE_URL/links", name = "Links" },
    { url = "$BASE_URL/atom.xml", name = "Feed" },
]
anpu_date_format = "%B, %e %Y"
